repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        language: system
        entry: pytest -v
        always_run: true
        pass_filenames: false
        stages: [commit]
